OusLabBlog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
import backend,posts
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap 
from django.views.generic.base import TemplateView

from frontend.models import BlogSitemap

from posts.models import Post

sitemaps = {
    'static': BlogSitemap,
}


info_dict = {
    'queryset': Post.objects.filter(deleted=False,published=True),
}

urlpatterns = [
    path('', include('frontend.urls')),
    re_path(r'^dashboard/', include('backend.urls')),
    re_path(r'^dashboard/posts', include('posts.urls')),
    re_path(r'^dashboard/tags', include('tags.urls')),
    re_path(r'^dashboard/categories', include('categories.urls')),
    re_path(r'^dashboard/comments', include('comments.urls')),
    re_path(r'^dashboard/library', include('library.urls')),
    re_path(r'^dashboard/viewlogs', include('views_log.urls')),


    path('login', backend.views.dashboard_login, name='dashboard_login'),
    path('logout', backend.views.dashboard_logout, name='dashboard_logout'),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    
    #path('sitemap.xml', sitemap, {'sitemaps': {'blog': GenericSitemap(info_dict, priority=0.6)}}, name='django.contrib.sitemaps.views.sitemap'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    path("robots.txt",TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), ),

    
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

frontend/urls.py
from django.urls import path

from . import views
from comments.views import comment_store

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/<str:post_url>', views.post_details, name='post_details'),
    path('tech_snippets', views.tech_snippets, name='tech_snippets'),
    path('posts/tag/<int:tag_id>', views.postByTag, name='postByTag'),
    path('posts/categorie/<int:categorie_id>', views.postByCategorie, name='postByCategorie'),
    path('comments/send/<int:post_id>', comment_store, name='comment_store'),
    path('aboutme', views.aboutme, name='aboutme'),
    path('privacy_policy', views.privacy_policy, name='privacy_policy'),
    path('search', views.post_search, name='post_search'),
]

tags/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.tag_list, name='tag_list'),
    path('/create', views.tag_create, name='tag_create'),
    path('/store', views.tag_store, name='tag_store'),
    path('/delete/<int:tag_id>', views.tag_delete, name='tag_delete'),
    path('/edit/<int:tag_id>', views.tag_edit, name='tag_edit'),
    path('/update/<int:tag_id>', views.tag_update, name='tag_update'),
]

frontend/models.py
from django.db import models

from django.contrib.sitemaps import Sitemap
from posts.models import Post
from django.urls import reverse


class BlogSitemap(Sitemap):
    changefreq = "never"
    priority = 0.6

    def items(self):
        return Post.objects.filter(deleted=False, published=True)

    def lastmod(self, obj):
        return obj.published_at

    def location(self, item):
        return '/posts/%s' % (item.url_title)

tags/models.py
from django.db import models

from django.contrib.auth.models import User
from django.utils.deconstruct import deconstructible
from posts.models import Post
import random
import os


class Tag(models.Model):
    name = models.CharField(max_length=250)
    posts = models.ManyToManyField(Post)

frontend/views.py
from django.shortcuts import render
from django.http import HttpResponse
import os.path
from posts.models import Post
from tags.models import Tag
from categories.models import Categorie
from django.http import HttpResponseRedirect
from comments.forms import CommentForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from frontend.decorators import track_views
from django.db.models import Q


@track_views
def index(request):

    posts_list = Post.objects.filter(deleted=False, published=True, post_type="Project").order_by('-published_at')
    page = request.GET.get('page', 1)
    paginator = Paginator(posts_list, 8)

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'frontend/index.html', {'posts': posts})


@track_views
def tech_snippets(request):

    posts_list = Post.objects.filter(deleted=False, published=True, post_type="Tech Snippet").order_by('-published_at')
    page = request.GET.get('page', 1)
    paginator = Paginator(posts_list, 20)

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'frontend/tech_snippets.html', {'posts': posts})


@track_views
def post_details(request, post_url):

    post = Post.objects.filter(url_title=post_url, published=True).order_by('-published_at').first()
    if not post:
        return HttpResponseRedirect('/')
    form = CommentForm()
    return render(request, 'frontend/post_details.html', {'post': post, 'form': form})


@track_views
def postByTag(request, tag_id):

    tag = Tag.objects.get(id=tag_id)
    posts_list = tag.posts.filter(deleted=False, published=True)
    page = request.GET.get('page', 1)
    paginator = Paginator(posts_list, 8)

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'frontend/index.html', {'posts': posts})


@track_views
def postByCategorie(request, categorie_id):

    categorie = Categorie.objects.get(id=categorie_id)

    posts_list = categorie.posts.filter(deleted=False, published=True)
    page = request.GET.get('page', 1)
    paginator = Paginator(posts_list, 8)

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'frontend/index.html', {'posts': posts})


@track_views
def aboutme(request):
    return render(request, 'frontend/aboutme.html')


@track_views
def privacy_policy(request):
    return render(request, 'frontend/privacy_policy.html')


def post_search(request):

    if request.method == 'GET':
        keyword = request.GET.get('keyword')
        if len(keyword) >= 3 and keyword not None:
            posts_list = Post.objects.filter(Q(title__icontains=keyword) | Q(description__icontains=keyword), Q(published=True), Q(deleted=False))

            if len(posts_list) <= 0:
                return HttpResponseRedirect('/')

            page = request.GET.get('page', 1)
            paginator = Paginator(posts_list, 8)

            try:
                posts = paginator.page(page)
            except PageNotAnInteger:
                posts = paginator.page(1)
            except EmptyPage:
                posts = paginator.page(paginator.num_pages)

            return render(request, 'frontend/index.html', {'posts': posts})

    return HttpResponseRedirect('/')

templates/frontend/aboutme.html
{% extends 'frontend/layouts/base.html' %}

{% block css %}

{% endblock%}

{% block title %} About me {% endblock %}

{% block metadata %}
  <meta content="About me page" name='description'/>
  <meta content='OusLab, Oussama Ousmoi' name='keywords'/>

  <meta property="og:title" content="About me" />
  <meta property="og:type" content="text/html" />
  <meta property="og:url" content="http://{{ request.get_host}}" />
  <meta property="og:image" content="http://{{ request.get_host}}/static/frontend/img/logo_ouslab.png" />
{% endblock %}

{% block content %}

  
<div class="container">
  <!--PAGE TITLE-->

<div class="row">
  <div class="span12">
  <div class="page-header">
      <h1>
        About me
    </h1>
  </div>
  </div>
</div>

<!-- /. PAGE TITLE-->

<div class="row" style="min-height: 570px;">



    <span class="span6">
      <img src="/static/frontend/img/me.jpg" width="350px" style="border-radius: 10px;">
    </span>


    <span class="span6">



    <h3></h3>

        <address>
        <!-- <strong>About me</strong><br> -->
          My name is <a href="javascript:void(0)">Oussama Ousmoi</a>, I'm a computer engineer and electronics enthusiast. <br>
          I love tinkering with things since my childhood. <br>
          I was born in Azrou, Morocco a small yet beautiful and all green city. <br><br>

          I'll be sharing some of my projects and tech snippets through out this blog. <br><br>

          Thank you for stopping by, feel free to contact me through my social media networks, 
          and i appreciate your support. <br><br>

          Cheers <br>
          <a href="javascript:void(0)">OusLab </a> <br>
        
        </address>      
      <div class="social_networks">
        <a href="https://youtube.com/foxmjay"  target="_blank"><span>Youtube</span></a>
        <a href="https://www.facebook.com/OusLabCom" target="_blank" ><span>Facebook</span></a>
        <a href="https://github.com/foxmjay" target="_blank"><span>Github</span></a>
        <a href="mailto:foxmjay@gmail.com" target="_blank"><span>Email</span></a>
        <a href="http://linkedin.com" target="_blank"><span>Linkedin</span></a>

      </div>

    </span>

</div>

<div class="row" style="min-height: 570px;">


  <span class="span6"></span>
  <span class="span6">

    {% include "frontend/buymeacoffee.html" %}

  </span>
  
</div>

</div>

<!-- /.Row View -->

{% endblock %}

templates/frontend/buymeacoffee.html
<div class="side-bar">
    
</div>

templates/frontend/donate.html
<div class="side-bar">
    <h3>Donate $5</h3>

    <!-- <div id="payment-buttons"  style="margin: 10px 40px;"></div>
        <script src=""></script>
        <script> 
  
          paypal.Buttons({
               createOrder: function(data, actions) {
              return actions.order.create({
                  purchase_units: [
                      {
                          amount: {
                              currency_code: "USD",
                              value: "5"
                          }
                      }
                  ]
              });
          }
          }).render('#payment-buttons');
      </script> -->

</div>

templates/frontend/index.html
{% extends 'frontend/layouts/base.html' %}

{% block title %} Home {% endblock %}

{% block metadata %}
  <meta content="My name is Oussama Ousmoi and this is my Blog page that i call OusLab, it's my gateway to share some of my projects and hobbies with the Internet" name='description'/>
  <meta content='OusLab, Oussama Ousmoi' name='keywords'/>

  <meta property="og:title" content="Home" />
  <meta property="og:type" content="text/html" />
  <meta property="og:url" content="http://{{ request.get_host}}" />
  <meta property="og:image" content="http://{{ request.get_host}}/static/frontend/img/logo_ouslab.png" />

{% endblock %}


{% block css %}
{% endblock %}

{% block content %}

  
<div class="container">

<div class="row">


  <div class="span9">
    
    {% for post in posts %}

      {% if post.post_type == "Project" %}
        {% include "frontend/post_list_template.html" %}
      {% elif post.post_type == "Tech Snippet" %}
        {% include "frontend/snippet_list_template.html" %}
      {% endif %}

    {% endfor %}

    <!--Pagination-->
    {% if posts.has_other_pages %}
    <div class="pagination">
      <ul>
        {% if posts.has_previous %}
        <li>
          <a href="?page={{ posts.previous_page_number }}{% if request.GET.keyword %}&keyword={{ request.GET.keyword }}{% endif %}">Prev</a>
        </li>
        {% else %}
          <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in posts.paginator.page_range %}
          {% if posts.number == i %}
            <li class="active">
              <a href="javascript:void(0);">{{ i }}</a>
            </li>
          {% else %}           
            <li>
              <a href="?page={{ i }}{% if request.GET.keyword %}&keyword={{ request.GET.keyword }}{% endif %}">{{ i }}</a>
            </li>
          {% endif %}
        {% endfor %}
        {% if posts.has_next %}
          <li>
            <a href="?page={{ posts.next_page_number }}{% if request.GET.keyword %}&keyword={{ request.GET.keyword }}{% endif %}">Next</a>
          </li>
        {% else %}
          <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
      </ul>
    </div>
    {% endif %}	

  <!--/.Pagination-->
  </div>	

  <div class="span3">

    <div class="side-bar">

      <h3>Categories</h3>
        {% for categorie in categorie_list %}
          <a href="/posts/categorie/{{categorie.id}}">{{ categorie.name  }}</a>, 
        {% endfor %}

    </div>


    <div class="side-bar">
      <h3>Tags</h3>
      {% for tag in tag_list %}
      <a href="/posts/tag/{{tag.id}}">{{tag.name}}</a>, 
      {% endfor %}
    </div>

    {% include "frontend/buymeacoffee.html" %}

    {% include "frontend/recent_posts.html" %}

    
    {% include "frontend/ads/side_ads_gitkraken.html" %}
    {% include "frontend/ads/side_ads.html" %}

    <!-- {% include "frontend/donate.html" %} -->

  </div>

  
  <!--==================-->
</div>
</div>

<!-- /.Row View -->

{% endblock %}

templates/frontend/post_details.html
{% extends 'frontend/layouts/base.html' %}

{% block css %} 

<!-- <link rel="stylesheet" href="/static/frontend/css/prism.css"> -->

<style>
  h1 {
    /* font-weight: bolder; */
    font-size: 40px;
    padding-top: 10px;
  }

  .ql-align-center p{
    display: block;
    margin-left: auto;
    margin-right: auto;
    width: 50%;
  }

  .content_style img {
      width: 25%;
  }

  .img-overlay {
      position: fixed;
      top: 10%;
      max-height: 80%;
      left: 50%;
      transform: translate(-50%, 0) scale(0, 0);
      z-index: 10;
      box-shadow: 0 10px 20px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23);
      transition: all .3s ease;
  }

  .overlay-dark {
      left: 0;
      top: 0;
      position: fixed;
      background-color: #000;
      opacity: .9;
      width: 100%;
      height: 100%;
      z-index: 5;
      display: none;
  }

  pre {
    background-color: #bbddc7;
    width: 95%;
    max-height: 300px;
    overflow: auto;
    color: black;
    /* resize:vertical; */
}

iframe {
  width: 100%;
  height: 500px;
}

.IN-widget span{
  
  width: 100px;
  height: 30px;
  padding: 20px 20px !important;
  background-color: #0073b1 ;
  border-radius: 5px;
}

</style>


{% endblock %}

{% block title %} {{ post.title }} {% endblock %}

{% block metadata %}
  <meta content="{{ post.description }}" name='description'/>
  <meta content='OusLab , Oussama Ousmoi , {% for tag in post.tag_set.all %}{{tag.name}} , {% endfor %}  ' name='keywords'/>

  <meta property="fb:admins" content=""/>
  <meta property="og:title" content="{{ post.title }}" />
  <meta property="og:description" content="{{ post.description }}" />
  <meta property="og:type" content="text/html" />
  <meta property="og:url" content="{{ request.build_absolute_uri }}" />
  <meta property="og:image" content="http://{{ request.get_host}}{% if post.front_image  %}{{post.front_image.url}} {% endif %}" />
{% endblock %}

{% block content %}

  
<div class="container">

<div class="row">

	
  <div class="span9">
    <!--Blog Post-->
    <div class="blog-post">
       <h1>{{post.title}}</h1> 

      <div class="postmetadata">
        <ul>
            <li>
              <i class="icon-user"></i> <a href="#">{{ post.owner.username}}</a>
            </li>

            <li>
               <i class="icon-calendar"></i>{{ post.published_at}}
            </li>

            <li>
              <!-- <i class="icon-comment"></i> <a href="#">{{ post.comment_set.count }} Comments</a> -->
              <i class="icon-comment"></i> <a href="#"><span class="fb-comments-count" data-href="{{ request.build_absolute_uri }}"></span> Comments</a>

            </li>
            <li>
              <i class="icon-tags"></i>
              {% for tag in post.tag_set.all %}
                <a href="/posts/tag/{{tag.id}}">{{tag.name}}</a>,
              {% endfor %} 
               
            </li>
        </ul>
      </div>


    
        <img style="border-radius: 10px;"  src="{% if post.front_image  %}{{post.front_image.url}} {% endif %}" alt="{% for tag in post.tag_set.all %}{{tag.name}}_{% endfor %}" loading="lazy" onerror='this.src="/static/frontend/img/img_notfound.png"' >
        <p style="font-size: 18px; padding-bottom: 20px;">{{ post.description}}</p>	

        <div class="content_style">
          {{ post.content | safe}}
        </div>
        
    </div>

    <div class="overlay-dark"></div>
    <img class="img-overlay"> 

    <!--/.Blog Post-->
    
    <div class="comments">

      <script src="https://platform.linkedin.com/in.js" type="text/javascript">lang: en_US</script>
      <script type="IN/Share" data-url="{{ request.build_absolute_uri }}"></script>

      <div class="fb-share-button" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-size="large"><a target="_blank" href="" class="fb-xfbml-parse-ignore">Share</a></div>

      <div class="fb-like" data-href="" data-width="" data-layout="standard" data-action="like" data-size="large" data-share="false"></div>


      <h2>Comments :</h2>


      <div class="post-footer">
        <section id="isso-thread"></section>
        <script data-isso="https://isso.ouslab.com/" data-isso-vote="true"  data-isso-css="true"  data-isso-require-author="true" src="https://isso.ouslab.com/js/embed.min.js"></script>
      </div>
    
    </div>

    <!--Comments-->

   
    <!-- <div class="comments">
      {% for comment in post.comment_set.all %}
      <div class="media">
         <a href="#" class="pull-left"><img src="/static/frontend/img/img-60x60.jpg" class="media-object" alt='' /></a>
        <div class="media-body">
          <div class="postmetadata" style="margin-bottom: 0px;">
            <ul>
                <li>
                  <i class="icon-user"></i> <a href="javascript:void(0);">{{ comment.username }}</a>
                </li>
    
                <li>
                   <i class="icon-calendar"></i>{{ comment.created_at}}  
                </li>
            </ul>
          </div>
          {{ comment.message}}
        </div>
      </div>
      {% endfor %}
     
      {% for message in messages %}
        <div class="alert alert-block alert-info">
            <p>{{ message }} </p>
            {% if form.errors %} 
                {{ form.errors.as_ul }}
            {% endif %}
        </div>
      {% endfor %}
     

      <form action='/comments/send/{{ post.id }}' method='POST' id='form_id' class='form-signin' autocomplete='on'>
        {% csrf_token %}
         <input class="span8"  type="text" placeholder="Name" id="username" name="username" value="{% if form %}{{form.username.value}}{% endif %}"  required/> 
         <input class="span8" type="email" placeholder="Email" required id="email" name="email" value="{% if form %}{{form.email.value}}{% endif %}" required /> 
         <textarea class="span8" rows="10" placeholder="Message" id="message" name="message" required > {% if form %}{{form.message.value}}{% endif %} </textarea>
         <br>
         {{form.captcha}}

        <button type="submit" class="btn btn-large btn-primary">Submit</button>

    </form>

     

    </div> -->

    <!--/.Comments-->
    
  </div>	



  <div class="span3">
    <div class="side-bar">

      <h3>Categories</h3>
      <ul class="nav nav-list">
        {% for categorie in post.categorie_set.all %}
          <li><a href="/posts/categorie/{{categorie.id}}">{{ categorie.name  }}</a></li>
        {% endfor %}
      </ul>

    </div>


    <div class="side-bar">
      <h3>Tags</h3>

      {% for tag in post.tag_set.all %}
        <a href="/posts/tag/{{tag.id}}">{{tag.name}}</a>,
      {% endfor %}
    </div>

    {% include "frontend/buymeacoffee.html" %}

    {% include "frontend/recent_posts.html" %}

    {% include "frontend/ads/side_ads.html" %} 

  </div>

  
  <!--==================-->
</div>

</div>


<!-- /.Row View -->

{% endblock %}

{% block js %}



<script src="/static/frontend/js/image-popup.js"></script>

{% endblock %}

templates/frontend/post_list_template.html
<div class="blog-post">
    <a  href="/posts/{{ post.url_title }}"><h2>{{ post.title}}</h2></a>

    <div class="postmetadata">
      <ul>
          <li>
            <i class="icon-user"></i> <a href="#">{{ post.owner.username}}</a>
          </li>

          <li>
             <i class="icon-calendar"></i>{{ post.published_at}}
          </li>

          <!-- <li> -->
            <!-- <i class="icon-comment"></i> <a href="#">{{ post.comment_set.count }} Comments</a> -->
            <!-- <i class="icon-comment"></i> <a href="#"><span class="fb-comments-count" data-href="{{ request.get_host }}/posts/{{ post.url_title }}"></span>  Comments</a> -->

          <!-- </li>  -->
          <li>
            <i class="icon-tags"></i>
            {% for tag in post.tag_set.all %}
              <a href="/posts/tag/{{tag.id}}">{{tag.name}}</a>,
            {% endfor %} 
             
          </li>
      </ul>
    </div>

    <div class="post_image">
      <a  href="/posts/{{ post.url_title }}">
        <img style="border-radius: 10px;" src="{% if post.front_image  %}{{post.front_image.url}} {% endif %}" alt="{% for tag in post.tag_set.all %}{{tag.name}}_{% endfor %}" loading="lazy" onerror='this.src="/static/frontend/img/img_notfound.png"'>
      </a>
    </div>

    <div class="post_description"> 
      <p style="font-size: 18px;">{{ post.description}}<br> <a class="btn" style="background: #62a779; color: aliceblue; text-shadow: none;" href="/posts/{{ post.url_title }}">Read More</a>			</p>
    </div>

  </div>

templates/frontend/recent_posts.html
<div class="side-bar">
    <h3>Recent Posts</h3>
    {% for rp in recent_posts %}
    <div  style="padding-bottom:5px;">
      <div class="side-bar-image" >
        <a href="/posts/{{ rp.url_title }}"><img style="border-radius: 5px;" src="{% if rp.front_image  %}{{rp.front_image.url}} {% endif %}" alt="{% for tag in rp.tag_set.all %}{{tag.name}}_{% endfor %}" loading="lazy" onerror='this.src="/static/frontend/img/img_notfound.png"'></a>
      </div>
      <div class="side-bar-title">
        <a href="/posts/{{ rp.url_title }}"> <p style="color: #62a779;"> {{ rp.title }} </p></a>
      </div>
      <div style="width: 300px; padding-top: 15px;">
      <small><i class="icon-user"></i> <a href="#"><span style="color: grey;"> {{ rp.owner.username }}</span> </a>, <i class="icon-calendar"></i>{{ rp.published_at }}</small>
    </div> 
    </div>
    <hr>
    {% endfor %}

    <!-- <ul class="recent-post">
      {% for rp in recent_posts %}
        <li><a href="/posts/{{ rp.url_title }}" ><strong style="color: #62a779;">{{ rp.title }} </strong></a>
          <small><i class="icon-user"></i> <a href="#"><span style="color: grey;"> {{ rp.owner.username }}</span> </a>, <i class="icon-calendar"></i>{{ rp.published_at }}</small>
        </li>
      {% endfor %}		

    </ul> -->

</div>

templates/frontend/snippet_list_template.html
<div class="blog-post" style="margin-bottom: 0; padding: 0 0;">
    <a  href="/posts/{{ post.url_title }}"><h2 style="margin: 10px 0;"> <b>{{ post.title}}</b></h2></a>
    <p style="margin: 0 0;">{{ post.description}}</p>	 

    <div class="postmetadata" style="margin-bottom: 0;padding: 10px 0;">
      <ul>
          <li>
            <i class="icon-user"></i> <a href="#">{{ post.owner.username}}</a>
          </li>

          <li>
              <i class="icon-calendar"></i>{{ post.published_at}}
          </li>

          <!-- <li>
            <i class="icon-comment"></i> <a href="#">{{ post.comment_set.count }} Comments</a>
          </li> -->
          <li>
            <i class="icon-tags"></i>
            {% for tag in post.tag_set.all %}
              <a href="/posts/tag/{{tag.id}}">{{tag.name}}</a>,
            {% endfor %} 
              
          </li>
      </ul>
    </div>
  </div>

templates/frontend/tech_snippets.html
{% extends 'frontend/layouts/base.html' %}

{% block title %} Tech snippets {% endblock %}

{% block metadata %}
  <meta content="My name is Oussama Ousmoi and this is my Blog page that i call OusLab, it's my gateway to share some of my projects and hobbies with the Internet" name='description'/>
  <meta content='OusLab, Oussama Ousmoi' name='keywords'/>

  <meta property="og:title" content="Tech snippets" />
  <meta property="og:type" content="text/html" />
  <meta property="og:url" content="http://{{ request.get_host}}" />
  <meta property="og:image" content="http://{{ request.get_host}}/static/frontend/img/logo_ouslab.png" />

{% endblock %}

{% block content %}

  
<div class="container">
  <!--PAGE TITLE-->


<div class="row">


  <div class="span9">
    <!--Blog Post-->
    {% for post in posts %}
    <div class="blog-post" style="margin-bottom: 0; padding: 0 0;">
     <a  href="/posts/{{ post.url_title }}"><h2 style="margin: 10px 0;"> <b>{{ post.title}}</b></h2></a>
     <p style="margin: 0 0;">{{ post.description}}</p>	 

      <div class="postmetadata" style="margin-bottom: 0;padding: 10px 0;">
        <ul>
            <li>
              <i class="icon-user"></i> <a href="#">{{ post.owner.username}}</a>
            </li>

            <li>
               <i class="icon-calendar"></i>{{ post.published_at}}
            </li>

            <li>
              <i class="icon-comment"></i> <a href="#">{{ post.comment_set.count }} Comments</a>
            </li>
            <li>
              <i class="icon-tags"></i>
              {% for tag in post.tag_set.all %}
                <a href="/posts/tag/{{tag.id}}">{{tag.name}}</a>,
              {% endfor %} 
               
            </li>
        </ul>
      </div>



    </div>

   {% endfor %}
    <!--===============-->

  
    <!--/.Blog Post-->

    <!--Pagination-->
    {% if posts.has_other_pages %}
    <div class="pagination">
      <ul>
        {% if posts.has_previous %}
        <li>
          <a href="?page={{ posts.previous_page_number }}">Prev</a>
        </li>
        {% else %}
          <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in posts.paginator.page_range %}
          {% if posts.number == i %}
            <li class="active">
              <a href="javascript:void(0);">{{ i }}</a>
            </li>
          {% else %}           
            <li>
              <a href="?page={{ i }}">{{ i }}</a>
            </li>
          {% endif %}
        {% endfor %}
        {% if posts.has_next %}
          <li>
            <a href="?page={{ posts.next_page_number }}">Next</a>
          </li>
        {% else %}
          <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
      </ul>
    </div>
    {% endif %}	

  <!--/.Pagination-->
  </div>	



  <div class="span3">
    <div class="side-bar">

      <h3>Categories</h3>
        {% for categorie in categorie_list %}
          <a href="/posts/categorie/{{categorie.id}}">{{ categorie.name  }}</a>, 
        {% endfor %}

    </div>

    <div class="side-bar">
      <h3>Tags</h3>
      {% for tag in tag_list %}
      <a href="/posts/tag/{{tag.id}}">{{tag.name}}</a>, 
      {% endfor %}
    </div>

    {% include "frontend/buymeacoffee.html" %}

    {% include "frontend/recent_posts.html" %}

    {% include "frontend/ads/side_ads.html" %}
    
    <!-- {% include "frontend/donate.html" %} -->

  </div>

  <!--==================-->
</div>
</div>

<!-- /.Row View -->

{% endblock %}